### PR TITLE
adapt i915-sriov-dkms to kernel v6.12

### PR DESCRIPTION
**Pull request by recallmenot**
merge / implement:

762f8c13b8ca4b861d28a529fa56b7960d71b892
drm/{i915,xe}: Implement fbdev client callbacks

1da86618bdce301d23e89ecce92161f9d3b3c5e7
fs: Convert aops->write_begin to take a folio

a0634663d09abcda84eae37e9817490628a034c9
drm/nouveau: Do not set struct drm_mode_config_funcs.output_poll_changed

367cf0d8a6760e244f30d36cd3b2120f890837a7
drm/i915: Add flip done tracepoint

91103ca3750c346fe3a4f7b42aab9299d31d0460
drm/i915: Add async flip tracepoint

5f60d5f6bbc12e782fac78110b0ee62698f3b576
move asm/unaligned.h to linux/unaligned.h

cb787f4ac0c2e439ea8d7e6387b925f74576bdf8
[tree-wide] finally take no_llseek out

### CODE REVIEW

**Comment by recallmenot** [comment]
this will only work with v6.12 and above.

**Comment by bbaa-bbaa** [comment]
Thank you for your work.
I didn’t check my emails before starting the porting to 6.12, so we may have done some duplicate work. xD

**Comment by bbaa-bbaa** [comment]
The patch set containing `drm/{i915,xe}: Implement fbdev client callbacks` from [20240409081029.17843-1-tzimmermann@suse.de](https://patchwork.kernel.org/project/intel-gfx/cover/20240409081029.17843-1-tzimmermann@suse.de/) which introduced in Linux 6.10 seems to have other changes related to fbdev, but I can't get this patch set to work properly. Do you have any ideas?

[b5757a5](https://github.com/gregkh/linux/commit/b5757a5be2fac24f5c138e8ddb3b2c7be8ba1cb3) `drm: Remove struct drm_driver.lastclose`  say that the lastclose callback in struct drm_driver is unused. Can we simply remove `lastclose`?

```
Nov 16 14:50:11 archserver kernel: ------------[ cut here ]------------
Nov 16 14:50:11 archserver kernel: WARNING: CPU: 2 PID: 401 at kernel/workqueue.c:4192 cancel_delayed_work_sync+0xdc/0xf0
Nov 16 14:50:11 archserver kernel: Modules linked in: mt792x_lib mt76_connac_lib snd_compress crct10dif_pclmul ac97_bus crc32_pclmul mt76 snd_pcm_dmaengine polyval_clmulni polyval_generic snd_hda_intel ghash_clmulni_intel snd_intel_dspcfg mac80211 sha512_ssse3 snd_intel_sdw_acpi sha1_ssse3 snd_hda_codec aesni_intel gf128mul snd_hda_core crypto_simd r8169 cryptd snd_hwdep iTCO_wdt libarc4 snd_pcm rapl intel_pmc_bxt realtek mei_hdcp mei_pxp ee1004 spi_nor snd_timer iTCO_vendor_support i915(OE+) intel_cstate mdio_devres cfg80211 intel_uncore mtd mei_me wmi_bmof snd intel_lpss_pci i2c_i801 libphy pcspkr rfkill intel_lpss i2c_smbus soundcore i2c_mux mei idma64 intel_gtt intel_pmc_core intel_vsec pmt_telemetry pmt_class pinctrl_alderlake acpi_tad acpi_pad mac_hid tcp_bbr pkcs8_key_parser i2c_dev sg crypto_user loop dm_mod nfnetlink ip_tables x_tables hid_generic usbhid xe btrfs blake2b_generic drm_ttm_helper libcrc32c ttm crc32c_generic i2c_algo_bit xor raid6_pq gpu_sched drm_buddy drm_suballoc_helper drm_gpuvm drm_exec nvme crc32c_intel
Nov 16 14:50:11 archserver kernel:  drm_display_helper sha256_ssse3 spi_intel_pci nvme_core spi_intel cec xhci_pci nvme_auth xhci_pci_renesas video wmi
Nov 16 14:50:11 archserver kernel: CPU: 2 UID: 0 PID: 401 Comm: (udev-worker) Tainted: G     U     OE      6.11.8-zen1-2-zen #1 1400000003000000474e5500b8363362750b033d
Nov 16 14:50:11 archserver kernel: Tainted: [U]=USER, [O]=OOT_MODULE, [E]=UNSIGNED_MODULE
Nov 16 14:50:11 archserver kernel: Hardware name: Maxsun Default string/MS-Terminator B760M D4, BIOS H6.3G 08/12/2024
Nov 16 14:50:11 archserver kernel: RIP: 0010:cancel_delayed_work_sync+0xdc/0xf0
Nov 16 14:50:11 archserver kernel: Code: a8 10 75 0e 48 8d 7c 24 20 e8 d0 4a fd 00 eb 88 f3 90 4c 89 e7 e8 24 9f 05 00 84 c0 74 f2 e9 75 ff ff ff 0f 0b e9 65 ff ff ff <0f> 0b e9 67 ff ff ff 0f 0b eb cf e8 e4 80 fc 00 0f 1f 40 00 90 90
Nov 16 14:50:11 archserver kernel: RSP: 0018:ffffa44cc096f5e0 EFLAGS: 00010246
Nov 16 14:50:11 archserver kernel: RAX: 0000000000000000 RBX: ffff8a21042fe730 RCX: 0000000000000000
Nov 16 14:50:11 archserver kernel: RDX: 000fffffffe00000 RSI: ffffa44cc096f5e0 RDI: ffffa44cc096f628
Nov 16 14:50:11 archserver kernel: RBP: 0000000000000000 R08: 0000000000000200 R09: ffff8a2106cfcd38
Nov 16 14:50:11 archserver kernel: R10: ffffa44cc096f828 R11: 0000000000000040 R12: ffff8a21042fe730
Nov 16 14:50:11 archserver kernel: R13: 0000000000000002 R14: ffff8a21042fb000 R15: ffff8a2106288000
Nov 16 14:50:11 archserver kernel: FS:  00007f6e2ab27880(0000) GS:ffff8a4000300000(0000) knlGS:0000000000000000
Nov 16 14:50:11 archserver kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Nov 16 14:50:11 archserver kernel: CR2: 00007f6e29670760 CR3: 000000010735a000 CR4: 0000000000f50ef0
Nov 16 14:50:11 archserver kernel: PKRU: 55555554
Nov 16 14:50:11 archserver kernel: Call Trace:
Nov 16 14:50:11 archserver kernel:  <TASK>
Nov 16 14:50:11 archserver kernel:  ? cancel_delayed_work_sync+0xdc/0xf0
Nov 16 14:50:11 archserver kernel:  ? __warn.cold+0x8e/0xf5
Nov 16 14:50:11 archserver kernel:  ? cancel_delayed_work_sync+0xdc/0xf0
Nov 16 14:50:11 archserver kernel:  ? report_bug+0xe7/0x210
Nov 16 14:50:11 archserver kernel:  ? handle_bug+0x58/0x90
Nov 16 14:50:11 archserver kernel:  ? exc_invalid_op+0x19/0xc0
Nov 16 14:50:11 archserver kernel:  ? asm_exc_invalid_op+0x1a/0x20
Nov 16 14:50:11 archserver kernel:  ? cancel_delayed_work_sync+0xdc/0xf0
Nov 16 14:50:11 archserver kernel:  drm_dp_cec_unset_edid+0x44/0x100 [drm_display_helper 1400000003000000474e5500ec2b0571b40b78e1]
Nov 16 14:50:11 archserver kernel:  intel_dp_detect+0x28c/0xb20 [i915 1400000003000000474e55002e24e14f216c0460]
Nov 16 14:50:11 archserver kernel:  ? i915_gem_object_wait_moving_fence+0x29/0x60 [i915 1400000003000000474e55002e24e14f216c0460]
Nov 16 14:50:11 archserver kernel:  drm_helper_probe_single_connector_modes+0x438/0x7b0
Nov 16 14:50:11 archserver kernel:  ? drm_client_modeset_probe+0x14f/0x1bc0
Nov 16 14:50:11 archserver kernel:  drm_client_modeset_probe+0x26d/0x1bc0
Nov 16 14:50:11 archserver kernel:  ? xa_store+0x37/0x50
Nov 16 14:50:11 archserver kernel:  ? i915_gem_context_open+0xf3/0x150 [i915 1400000003000000474e55002e24e14f216c0460]
Nov 16 14:50:11 archserver kernel:  __drm_fb_helper_initial_config_and_unlock+0x3b/0x490
Nov 16 14:50:11 archserver kernel:  ? drm_file_alloc+0x1b3/0x260
Nov 16 14:50:11 archserver kernel:  ? drm_client_init+0xe0/0x110
Nov 16 14:50:11 archserver kernel:  intel_fbdev_client_hotplug+0xa2/0xf0 [i915 1400000003000000474e55002e24e14f216c0460]
Nov 16 14:50:11 archserver kernel:  drm_client_register+0x7a/0xb0
Nov 16 14:50:11 archserver kernel:  intel_display_driver_probe+0x6c/0x80 [i915 1400000003000000474e55002e24e14f216c0460]
Nov 16 14:50:11 archserver kernel:  i915_driver_probe+0x817/0xd30 [i915 1400000003000000474e55002e24e14f216c0460]
Nov 16 14:50:11 archserver kernel:  pci_device_probe+0xf2/0x2c0
Nov 16 14:50:11 archserver kernel:  really_probe+0xdb/0x3b0
Nov 16 14:50:11 archserver kernel:  ? pm_runtime_barrier+0x54/0x90
Nov 16 14:50:11 archserver kernel:  ? __pfx___driver_attach+0x10/0x10
Nov 16 14:50:11 archserver kernel:  __driver_probe_device+0x78/0x110
Nov 16 14:50:11 archserver kernel:  driver_probe_device+0x1f/0x130
Nov 16 14:50:11 archserver kernel:  __driver_attach+0x91/0x1e0
Nov 16 14:50:11 archserver kernel:  bus_for_each_dev+0x10b/0x170
Nov 16 14:50:11 archserver kernel:  bus_add_driver+0x137/0x270
Nov 16 14:50:11 archserver kernel:  driver_register+0x72/0xd0
Nov 16 14:50:11 archserver kernel:  i915_init+0x23/0x90 [i915 1400000003000000474e55002e24e14f216c0460]
Nov 16 14:50:11 archserver kernel:  ? __pfx_i915_init+0x10/0x10 [i915 1400000003000000474e55002e24e14f216c0460]
Nov 16 14:50:11 archserver kernel:  do_one_initcall+0x58/0x310
Nov 16 14:50:11 archserver kernel:  do_init_module+0x60/0x230
Nov 16 14:50:11 archserver kernel:  idempotent_init_module+0x182/0x3a0
Nov 16 14:50:11 archserver kernel:  __x64_sys_finit_module+0x5e/0xb0
Nov 16 14:50:11 archserver kernel:  do_syscall_64+0x82/0x190
Nov 16 14:50:11 archserver kernel:  ? __x64_sys_openat+0x1f5/0x230
Nov 16 14:50:11 archserver kernel:  ? syscall_exit_to_user_mode+0x10/0x1f0
Nov 16 14:50:11 archserver kernel:  ? do_syscall_64+0x8e/0x190
Nov 16 14:50:11 archserver kernel:  ? exc_page_fault+0x81/0x190
Nov 16 14:50:11 archserver kernel:  entry_SYSCALL_64_after_hwframe+0x76/0x7e
Nov 16 14:50:11 archserver kernel: RIP: 0033:0x7f6e2ad261fd
Nov 16 14:50:11 archserver kernel: Code: ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d e3 fa 0c 00 f7 d8 64 89 01 48
Nov 16 14:50:11 archserver kernel: RSP: 002b:00007ffd0d904568 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
Nov 16 14:50:11 archserver kernel: RAX: ffffffffffffffda RBX: 00005db3a7d6c650 RCX: 00007f6e2ad261fd
Nov 16 14:50:11 archserver kernel: RDX: 0000000000000004 RSI: 00005db3a7d6b010 RDI: 0000000000000018
Nov 16 14:50:11 archserver kernel: RBP: 00007ffd0d904620 R08: 00007f6e2adf6b20 R09: 00007ffd0d9045b0
Nov 16 14:50:11 archserver kernel: R10: 00005db3a7d69b80 R11: 0000000000000246 R12: 00005db3a7d6b010
Nov 16 14:50:11 archserver kernel: R13: 0000000000020000 R14: 00005db3a7c6c390 R15: 00005db3a7d69b50
Nov 16 14:50:11 archserver kernel:  </TASK>
Nov 16 14:50:11 archserver kernel: ---[ end trace 0000000000000000 ]---
```

**Comment by recallmenot** [comment]
Didn't know you were already working on it.
I spoke too soon, I was happy to get it to build but you're right, it doesn't work, sorry, should have tested first.

This module is based on a pretty outdated version of i915 as it is and maintaining this will only get much harder if we let them drift further apart.
I'd like to port all changes to i915 from mainline but I can only start with that tomorrow...

**Comment by bbaa-bbaa** [comment]
In fact, the mainline i915 driver contains a lot of changes that depend on DRM and other subsystems. Porting all the changes from the mainline would break compatibility with older kernel versions or make maintenance more difficult.
The module is based on the linux-intel-lts 6.6 branch, which includes a backport of DRM from Linux 6.8. I once tried to get this 6.6 branch working on kernels between 6.6 and 6.7, but I couldn't find a way to make this module work properly. [6.6-base-bad-port](https://github.com/bbaa-bbaa/i915-sriov-dkms/tree/6.6-base-bad-port)
Moreover, Linux 6.12 is likely to be this year's LTS kernel, and Intel will probably have an official port of i915 for 6.12. We may just need to wait.

**Pull request closed without merging**
